# Generated by Django 4.1.6 on 2023-02-10 10:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.CharField(max_length=12)),
                ('adult', models.BooleanField(default=False)),
                ('backdrop_path', models.CharField(max_length=128)),
                ('original_language', models.CharField(max_length=16)),
                ('original_title', models.CharField(max_length=64)),
                ('genre_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('overview', models.CharField(max_length=1024)),
                ('popularity', models.FloatField(default=0)),
                ('poster_path', models.CharField(max_length=128)),
                ('release_date', models.DateField()),
                ('title', models.CharField(max_length=128)),
                ('video', models.BooleanField(default=False)),
                ('vote_average', models.FloatField()),
                ('vote_count', models.IntegerField()),
            ],
        ),
    ]
