# Generated by Django 4.1.6 on 2023-02-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvapp', '0003_rename_movie_id_movie_movieid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='backdrop_path',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre_ids',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(blank=True),
        ),
    ]
