# Generated by Django 4.1.6 on 2023-02-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvapp', '0004_alter_movie_backdrop_path_alter_movie_genre_ids_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default='0000-00-00'),
        ),
    ]
