# Generated by Django 4.1.6 on 2023-02-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvapp', '0005_alter_movie_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(blank=True, default='0000-00-00', null=True),
        ),
    ]
